_wandb:
    value:
        cli_version: 0.23.1
        e:
            3bvikm0trdvatfbeot6zemwtr28cxvf4:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "285765918720"
                email: s245414@dtu.dk
                executable: /Users/brorbruland/Desktop/MLOps_project/.venv/bin/python
                git:
                    commit: 03c0fc7d371b18bea331bf7dc95c269af052db49
                    remote: https://github.com/s246070/MLOps_project.git
                host: mac.students.clients.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: -m mlops_project.train_pickle
                python: CPython 3.13.5
                root: /Users/brorbruland/Desktop/MLOps_project/src
                startedAt: "2026-01-15T15:49:07.652856Z"
                writerId: 3bvikm0trdvatfbeot6zemwtr28cxvf4
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
            "2":
                - 1
                - 5
                - 50
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
data:
    value:
        processed_dir: data/processed
        raw_path: data/raw/Titanic-Dataset.csv
        train_test_split: 0.2
        train_val_split: 0.8
hyperparameters:
    value:
        batch_size: 32
        epochs: 500
        lr: 0.01
        optimizer: adam
        weight_decay: 0
model:
    value:
        name: LogisticRegression
paths:
    value:
        log_dir: logs
        model_dir: models
seed:
    value: 42
wandb:
    value:
        entity: null
        project: titanic
