_wandb:
    value:
        cli_version: 0.23.1
        e:
            8gfjyixf68oxbj94zs4h438lxoroq85i:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "285388275712"
                email: s245414@dtu.dk
                executable: /Users/brorbruland/Desktop/MLOps_project/.venv/bin/python
                git:
                    commit: e829873548ef3f57051a8477e7668096dc5a48ee
                    remote: https://github.com/s246070/MLOps_project.git
                host: mac.students.clients.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: -m mlops_project.train_pickle
                python: CPython 3.13.5
                root: /Users/brorbruland/Desktop/MLOps_project/src
                startedAt: "2026-01-15T14:01:01.988282Z"
                writerId: 8gfjyixf68oxbj94zs4h438lxoroq85i
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 500
lr:
    value: 0.01
optimizer:
    value: adam
weight_decay:
    value: 0
