defaults:
  - hyperparameters: default
  - model: logistic
  - _self_

seed: 42

data:
  raw_path: "data/raw/Titanic-Dataset.csv"
  processed_dir: "data/processed"
  train_test_split: 0.2
  train_val_split: 0.8

paths:
  model_dir: "models"
  log_dir: "logs"

wandb:
  project: "titanic"
  entity: null