name: "Run tests"

on:
  push:
    branches: [ master, main, tests ]
  pull_request:
    branches: [ master, main, tests ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.13, 3.12, 3.11]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Run tests with coverage
      run: |
        uv run coverage run -m pytest -v
        uv run coverage report -m

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
    - name: Install dependencies
      run: |
        uv sync --dev --locked

    - name: Test with pytest
      run: |
        uv run pytest -v